### ISSUE TITLE
idfc but this shit or rat or coded horribly

### ISSUE THREAD

**Issue by swagina** [TriizzyxOT/NEVERLOSE-CS2-FREE#3]
same problem its just not launching

**Comment by TriizzyxOT** [comment]
seems to be a system issue on your end. unable to reproduce issue, launches fine on win10 and win11 tested on multiple systems. please ensure you have windows defender real time protection disabled along with cloud based protection and uninstall any 3rd party antivirus as this may also affect launching as well.
